# Generated by Django 4.2.18 on 2026-05-28 08:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(unique=True, verbose_name='CI')),
                ('name', models.CharField(verbose_name='Имя')),
                ('is_it_service', models.BooleanField(verbose_name='IT-Услуга?')),
                ('is_active', models.BooleanField(verbose_name='Активена?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(unique=True, verbose_name='CI')),
                ('has_anonymized_data', models.BooleanField(verbose_name='Содержит обезличенные данные?')),
                ('ips', django.contrib.postgres.fields.ArrayField(base_field=netfields.fields.CidrAddressField(max_length=43, verbose_name='IP-адреса'), default=list, size=None)),
                ('is_active', models.BooleanField(verbose_name='Активен?')),
                ('name', models.CharField(verbose_name='Имя')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stands', to='network_access.system', verbose_name='Система')),
            ],
        ),
    ]
