# Generated by Django 4.2.18 on 2025-04-25 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import netfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='Публичный ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('creation_reason', models.TextField(verbose_name='Обоснование создания')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Группа Доступа',
                'verbose_name_plural': 'Группы Доступа',
            },
        ),
        migrations.CreateModel(
            name='AccessGroup2Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время утверждения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Связь Группы Доступа и Префикса',
                'verbose_name_plural': 'Связь Групп Доступа и Префиксов',
            },
        ),
        migrations.CreateModel(
            name='AccessGroup2PrefixSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch_resource_guid', models.CharField(max_length=128, verbose_name='ID Ресурса из архитектурного описания')),
                ('unactual_at', models.DateTimeField(blank=True, null=True, verbose_name='Время потери актуальности')),
                ('unactuality_reason', models.TextField(blank=True, null=True, verbose_name='Обоснование потери актуальности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGroupSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch_stand_guid', models.CharField(max_length=128, verbose_name='ID Стенда из архитектурного описания')),
                ('arch_component_guid', models.CharField(max_length=128, verbose_name='ID Компонента из архитектурного описания')),
                ('unactual_at', models.DateTimeField(blank=True, null=True, verbose_name='Время потери актуальности')),
                ('unactuality_reason', models.TextField(blank=True, null=True, verbose_name='Обоснование потери актуальности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Источник Группы Доступа',
                'verbose_name_plural': 'Источники Групп Доступа',
            },
        ),
        migrations.CreateModel(
            name='NetworkInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='Публичный ID')),
                ('creation_reason', models.TextField(verbose_name='Обоснование создания')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Время активации')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Сетевое Взаимодействие',
                'verbose_name_plural': 'Сетевые Взаимодействия',
            },
        ),
        migrations.CreateModel(
            name='NetworkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=128, unique=True, verbose_name='Публичный ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('creation_reason', models.TextField(verbose_name='Обоснование создания')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', netfields.fields.CidrAddressField(max_length=43, verbose_name='Префикс')),
                ('network_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network_access.networkzone', verbose_name='Сетевая Зона')),
            ],
            options={
                'verbose_name': 'Префикс',
                'verbose_name_plural': 'Префиксы',
            },
        ),
        migrations.CreateModel(
            name='NetworkInteractionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch_interaction_guid', models.CharField(max_length=128, unique=True, verbose_name='ID сущности из архитектурного описания')),
                ('creation_reason', models.TextField(verbose_name='Обоснование создания')),
                ('protocol_to_ports', models.TextField(help_text='{"TCP":["43","443"],"UDP":["444"]}', verbose_name='Связь протоколов и портов')),
                ('unactual_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата потери актуальности')),
                ('unactuality_reason', models.TextField(blank=True, null=True, verbose_name='Обоснование потери актуальности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('dst_network_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_interactions_where_dst', to='network_access.networkzone', verbose_name='Сетевая Зона назначения')),
                ('src_network_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_interactions_where_src', to='network_access.networkzone', verbose_name='Сетевая Зона источника')),
            ],
        ),
    ]
