# Generated by Django 4.2.18 on 2025-04-26 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("network_access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkinteraction",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь, создавший Сетевое Взаимодействие",
            ),
        ),
        migrations.AddField(
            model_name="networkinteraction",
            name="dst_access_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="network_interactions_where_dst",
                to="network_access.accessgroup",
                verbose_name="Группа Доступа назначения",
            ),
        ),
        migrations.AddField(
            model_name="networkinteraction",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="network_interaction",
                to="network_access.networkinteractionsource",
                verbose_name="Источник",
            ),
        ),
        migrations.AddField(
            model_name="networkinteraction",
            name="src_access_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="network_interactions_where_src",
                to="network_access.accessgroup",
                verbose_name="Группа Доступа источника",
            ),
        ),
        migrations.AddField(
            model_name="accessgroupsource",
            name="network_zones",
            field=models.ManyToManyField(
                related_name="access_groups",
                to="network_access.networkzone",
                verbose_name="Сетевые зоны",
            ),
        ),
        migrations.AddField(
            model_name="accessgroup2prefix",
            name="access_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="network_access.accessgroup",
                verbose_name="Группа Доступа",
            ),
        ),
        migrations.AddField(
            model_name="accessgroup2prefix",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор, утвердивший связь",
            ),
        ),
        migrations.AddField(
            model_name="accessgroup2prefix",
            name="prefix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="network_access.prefix",
                verbose_name="Префикс",
            ),
        ),
        migrations.AddField(
            model_name="accessgroup2prefix",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="network_access.accessgroup2prefixsource",
                verbose_name="Источник связи Группы Доступа и Префикса",
            ),
        ),
        migrations.AddField(
            model_name="accessgroup",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="network_access.accessgroupsource",
                verbose_name="Источник",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkinteraction",
            constraint=models.UniqueConstraint(
                fields=("src_access_group", "dst_access_group", "source"),
                name="network_access_networkinteraction_unique_network_interaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessgroup2prefix",
            constraint=models.UniqueConstraint(
                fields=("access_group", "prefix", "source"),
                name="network_access_accessgroup2prefix_unique_access_group_to_prefix",
            ),
        ),
    ]
