# Generated by Django 4.2.18 on 2025-04-26 11:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessOrchestratorPermission",
            fields=[],
            options={
                "permissions": [
                    (
                        "users.get_network_interaction",
                        "Могу получить Сетевое Взаимодействие",
                    )
                ],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.permission",),
            managers=[
                ("objects", django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
