# Generated by Django 4.2.18 on 2026-05-28 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullELTVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(verbose_name='Статус')),
                ('info', models.JSONField(null=True, verbose_name='Детали загрузки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Версия выгрузки',
                'verbose_name_plural': 'Версии выгрузок',
            },
        ),
        migrations.CreateModel(
            name='ELTSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(verbose_name='CI')),
                ('system_type', models.CharField(verbose_name='Тип системы')),
                ('name', models.CharField(verbose_name='Имя')),
                ('status', models.CharField(null=True, verbose_name='Статус')),
                ('is_it_service', models.BooleanField(blank=True, null=True, verbose_name='ИТ-Услуга?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('related_systems', models.ManyToManyField(to='elt.eltsystem', verbose_name='Связанные системы')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elt.fulleltversion', verbose_name='Версия')),
            ],
        ),
        migrations.CreateModel(
            name='ELTStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(verbose_name='CI')),
                ('sb_security_group', models.CharField(blank=True, null=True, verbose_name='Признак обезличенных данных')),
                ('status', models.CharField(null=True, verbose_name='Статус')),
                ('name', models.CharField(null=True, verbose_name='Имя')),
                ('subtype', models.CharField(blank=True, null=True, verbose_name='Подтип')),
                ('devices', models.TextField(blank=True, null=True, verbose_name='Связи с устройствами')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elt.eltsystem', verbose_name='AC')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elt.fulleltversion', verbose_name='Версия')),
            ],
        ),
        migrations.CreateModel(
            name='ELTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(null=True, verbose_name='Тип')),
                ('subtype', models.CharField(null=True, verbose_name='Подтип')),
                ('name', models.CharField(null=True, verbose_name='Имя')),
                ('ci', models.CharField(db_index=True, verbose_name='CI')),
                ('status', models.CharField(null=True, verbose_name='Статус')),
                ('ips', models.TextField(blank=True, null=True, verbose_name='Список IP-адресов')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elt.fulleltversion', verbose_name='Версия')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eltsystem',
            constraint=models.UniqueConstraint(fields=('ci', 'version'), name='unique_system_for_version'),
        ),
        migrations.AddConstraint(
            model_name='eltstand',
            constraint=models.UniqueConstraint(fields=('ci', 'version'), name='unique_stand_for_version'),
        ),
        migrations.AddConstraint(
            model_name='eltdevice',
            constraint=models.UniqueConstraint(fields=('ci', 'version'), name='unique_device_and_version'),
        ),
    ]
